name: quantum_restaurant
description: "A new Flutter project."
publish_to: 'none' 
version: 7.0.1+1 

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animation_wrappers: ^3.0.0
  flutter_bloc: ^9.1.1
  flutter_phoenix: ^1.1.1
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  grock: ^0.6.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  gridview_menu: ^1.0.6
  flutter_slidable: ^4.0.1
  animate_do: ^4.2.0
  image_picker: ^1.2.0
  flutter_spinbox: ^0.13.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  path: any
  path_provider: any
  share_plus: ^11.1.0
  image_gallery_saver_plus: ^4.0.1
  flutter_riverpod: ^2.6.1
  flutter_native_splash: ^2.4.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.4


flutter_native_splash:
  color: "#009946"
  image: assets/splash.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  
  assets:
    - assets/ItemCategory/
    - assets/
    - assets/food items/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
